name: CI

on:
  push:
    branches: # Run tests when PR is merged to one of the following branches
      - master
      - dev
  pull_request:
    branches: # Run for every pull-request
      - '**'

jobs:
  build:
    strategy:
      matrix:
        node: ['12', '10', '8', '13']
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache NPM/Yarn dependencies
        uses: actions/cache@preview
        with:
          path: node_modules
          key: node-${{ matrix.node }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            node-${{ matrix.node }}-yarn-
      - name: Check duplicates in yarn.lock
        if: matrix.node == '12'
        run: npx yarn-deduplicate --list --fail yarn.lock
      - name: Install Falcon dependencies
        run: yarn --non-interactive --frozen-lockfile
      - name: Lint project files
        if: matrix.node == '12'
        run: yarn lint
      - name: Run Falcon tests
        run: yarn test
      - name: Collect Code Coverage
        run: yarn coverage -t ${{ secrets.CODECOV_TOKEN }}
